---
- name: Operate on multiple namespaces
  include_tasks: gather_namespaces.yml
  when: use_namespaces|string == 'all' and export_namespaces|bool == true

- name: Operate on single namespace
  command: "echo {{ use_namespaces }}"
  register: namespaces
  when: use_namespaces|string != 'all' and export_namespaces|bool == true

- name: Export namespaces
  include_tasks: export_namespaces.yml
  when: export_namespaces|bool == true and import_namespaces|bool != true

- name: Import namespace contents
  include_tasks: import_namespaces.yml
  when: import_namespaces|bool == true and export_namespaces|bool != true
