---
- name: Operate on multiple namespaces
  include_tasks: gather_namespaces.yml
  when: use_namespaces|string == 'all' and export_namespaces|bool == true

- name: Operate on single namespace
  command: "echo {{ use_namespaces }}"
  register: namespaces
  when: use_namespaces|string != 'all' and export_namespaces|bool == true

- name: Export namespaces
  include_tasks: export_namespaces.yml
  when: export_namespaces|bool == true and import_namespaces|bool != true

- name: Import namespace contents
  include_tasks: import_namespaces.yml
  when: import_namespaces|bool == true and export_namespaces|bool != true

- name: Create test project
  include_tasks: create_test_data.yml
  when: remove_test_data|bool != true and create_test_data|bool == true and export_namespaces|bool != true and import_namespaces != true

- name: Remove test project
  include_tasks: remove_test_data.yml
  when: remove_test_data|bool == true and create_test_data|bool != true and export_namespaces|bool != true and import_namespaces != true